from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.auto_placement import create_auto_placements
from app.local_analysis import analyze_pdf
from app.models import ProcessingOptions


def main() -> None:
    parser = argparse.ArgumentParser(description="Run local QA analysis on real PDFs.")
    parser.add_argument("paths", nargs="+", help="PDF files or folders with PDF files")
    parser.add_argument(
        "--output",
        default="REAL_DOCUMENT_QA_REPORT.md",
        help="Markdown report path",
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=None,
        help="Optional limit for quick regression runs",
    )
    args = parser.parse_args()

    pdfs = collect_pdfs([Path(path) for path in args.paths])
    if args.max_files is not None:
        pdfs = pdfs[: args.max_files]
    lines = [
        "# Real Document QA Report",
        "",
        "Generated by `scripts/qa_real_documents.py`.",
        "",
        f"Total PDF files: {len(pdfs)}",
        "",
    ]

    for pdf in pdfs:
        lines.extend(analyze_one(pdf))

    output_path = Path(args.output)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(output_path)


def collect_pdfs(paths: list[Path]) -> list[Path]:
    pdfs: list[Path] = []
    for path in paths:
        if path.is_dir():
            pdfs.extend(sorted(path.rglob("*.pdf")))
        elif path.suffix.lower() == ".pdf":
            pdfs.append(path)
    return sorted(set(pdfs))


def analyze_one(path: Path) -> list[str]:
    lines = [f"## {path.name}", "", f"Path: `{path}`", ""]
    try:
        analyses = analyze_pdf(path, ocr_languages="rus+eng")
        placements = create_auto_placements(analyses, ProcessingOptions(use_ai=False))
    except Exception as exc:
        return [*lines, f"Status: `failed`", "", f"Error: `{exc}`", ""]

    candidates = [candidate for analysis in analyses for candidate in analysis.candidates]
    status = classify(candidates, placements, analyses)
    lines.extend(
        [
            f"Status: `{status}`",
            "",
            f"Pages: {len(analyses)}",
            f"Candidates: {len(candidates)}",
            f"Auto placements: {len(placements)}",
            "",
        ]
    )

    page_warnings = sorted({warning for analysis in analyses for warning in analysis.warnings})
    if page_warnings:
        lines.extend(["Warnings:", ""])
        lines.extend(f"- `{warning}`" for warning in page_warnings)
        lines.append("")

    for analysis in analyses:
        if not analysis.candidates and not analysis.warnings:
            continue
        lines.append(f"### Page {analysis.page_number}")
        lines.append("")
        lines.append(
            f"Text quality: `{analysis.text_quality}`, words: {len(analysis.words)}, lines: {len(analysis.lines)}"
        )
        lines.append("")
        for candidate in analysis.candidates[:8]:
            line_bbox = candidate.line_bbox.as_list() if candidate.line_bbox else None
            lines.append(
                f"- `{candidate.anchor}` | `{candidate.reason}` | confidence `{candidate.confidence:.2f}` | warnings `{', '.join(candidate.warnings) or 'none'}` | line `{line_bbox}`"
            )
        lines.append("")

    return lines


def classify(candidates, placements, analyses) -> str:
    if placements:
        return "auto_placement"
    if candidates:
        return "needs_review"
    if any(analysis.text_quality in {"ocr_failed", "no_text_layer"} for analysis in analyses):
        return "needs_review"
    return "no_signature_candidate"


if __name__ == "__main__":
    main()
